### ISSUE TITLE
1. Errors From Board Button: 

### ISSUE THREAD

**Issue by jumpingrabbit** [Conjoint-ly/trello-pivot#7]
When we click on the board button, nothing happens but we see the following error:
> captured_trace.js:487 Unhandled rejection Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document. at https://conjoint-ly.github.io/trello-pivot/connector.1bf5abe3.js:2:1615

We test in an incognito window. But we expect that the Power-Up to work without access to localStorage.

**Comment by jumpingrabbit** [comment]
We should check: if `localStorage` is not available, then we should use `sessionStorage`. 


Test in Edge, Firefox, Chrome when incognito.

**Comment by shockedbear-conjointly** [comment]
We don't need storage anymore, it's better to load fresh data on modal show
